sudo: false

language: php

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  - DEPS=lowest
  - DEPS=highest

install:
  - if [ "$DEPS" = "lowest" ]; then
      composer update -n --prefer-source --prefer-lowest;
    else
      composer update -n --prefer-source;
    fi;
  - composer show

script:
  - phpdbg -qrr vendor/bin/phpunit -c phpunit.xml.dist --coverage-text --coverage-clover build/logs/clover.xml
#  - php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_success:
  - composer require satooshi/php-coveralls
  - travis_retry php vendor/bin/coveralls -v

cache:
  directories:
